// Code generated by MockGen. DO NOT EDIT.
// Source: vacation_planner/reader (interfaces: DataReader)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "vacation_planner/models"

	gomock "github.com/golang/mock/gomock"
)

// MockDataReader is a mock of DataReader interface.
type MockDataReader struct {
	ctrl     *gomock.Controller
	recorder *MockDataReaderMockRecorder
}

// MockDataReaderMockRecorder is the mock recorder for MockDataReader.
type MockDataReaderMockRecorder struct {
	mock *MockDataReader
}

// NewMockDataReader creates a new mock instance.
func NewMockDataReader(ctrl *gomock.Controller) *MockDataReader {
	mock := &MockDataReader{ctrl: ctrl}
	mock.recorder = &MockDataReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataReader) EXPECT() *MockDataReaderMockRecorder {
	return m.recorder
}

// ReadData mocks base method.
func (m *MockDataReader) ReadData() ([]models.CityTemp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadData")
	ret0, _ := ret[0].([]models.CityTemp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadData indicates an expected call of ReadData.
func (mr *MockDataReaderMockRecorder) ReadData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadData", reflect.TypeOf((*MockDataReader)(nil).ReadData))
}
